[workspace]
members = ["projects/*"]
default-members = [
    "projects/forma-core",
    "projects/forma-parser",
    "projects/forma-wasm",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
